#! /bin/bash

if [ $(id -u) != 0 ];
	then echo "you are not running it as root"; exit;
fi;

if [ "$1" == "" ];
	then echo "no zone name specified, do dns_add_zone <name of zone>"; exit;
fi;

echo "zone \"$1.quinten-nouters.sb.uclllabs.be\" {
	type master;
	file \"/etc/bind/zone/$1.quinten-nouters.sb.uclllabs.be\";
};" >> /etc/bind/named.conf.local;

touch /etc/bind/zone/$1.quinten-nouters.sb.uclllabs.be;

echo "\$TTL 300
@	IN	SOA	ns.$1.quinten-nouters.sb.uclllabs.be. root.$1.quinten-nouters.sb.uclllabs.be (
	1	; Serial
	604800	; Refresh
	86400	; Retry
	2419200	; Expire
	300 )	; Negative Cache TTL
;
@	IN	NS	ns.$1.quinten.nouters.sb.uclllabs.be.
@	IN	NS	ns.quinten-nouter.sb.uclllabs.be.
ns	IN	A	193.191.177.225" >> /etc/bind/zone/$1.quinten-nouters.sb.uclllabs.be; 

echo "$1	IN	NS	ns.quinten-nouters.sb.uclllabs.be." >> /etc/bind/zone/db.quinten-nouters.sb.uclllabs.be;
